#!/bin/bash
name="10"
password="truKLdjsbJ5g7yyJ2X2R0o3a5HQJFuLk"
sshpass -p "$password" ssh -o StrictHostKeyChecking=no -p 2220 bandit"$name"@bandit.labs.overthewire.org '
base64 -d data.txt | grep -o -P "(?<=The password is ).*"
exit' 2>/dev/null
