#!/bin/bash
name="11"
password="IFukwKGsFW8MOq3IRFqrxE1hxTNEbUPR"
sshpass -p "$password" ssh -o StrictHostKeyChecking=no -p 2220 bandit"$name"@bandit.labs.overthewire.org '
cat data.txt | tr "[A-Za-z]" "[N-ZA-Mn-za-m]" | grep -o -P "[^ ]{32}";
exit' 2>/dev/null
