#!/bin/bash
name="6"
password="DXjZPULLxYr17uwoI01bNLQbtFemEgo7"
sshpass -p "$password" ssh -o StrictHostKeyChecking=no -p 2220 bandit"$name"@bandit.labs.overthewire.org '
cd /;
cat $(find . -group bandit6 -user bandit7 -size 33c 2>/dev/null);
exit' 2>/dev/null
