#!/bin/bash
name="8"
password="cvX2JJa4CFALtqS87jk27qwqGhBM9plV"
sshpass -p "$password" ssh -o StrictHostKeyChecking=no -p 2220 bandit"$name"@bandit.labs.overthewire.org '
sort data.txt | uniq -u
exit' 2>/dev/null
