#!/bin/bash
name="5"
password="koReBOKuIDDepwhWk7jZC0RTdopnAYKh"
sshpass -p "$password" ssh -o StrictHostKeyChecking=no -p 2220 bandit"$name"@bandit.labs.overthewire.org '
cd inhere;
correctFile=$(find -size 1033c)
cat "$correctFile" | grep "\w"
exit' 2>/dev/null
