#!/bin/bash
name="7"
password="HKBPTKQnIay4Fw76bEy8PVxKEDQRKTzs"
sshpass -p "$password" ssh -o StrictHostKeyChecking=no -p 2220 bandit"$name"@bandit.labs.overthewire.org '
fileContent=$(grep -o -P "(?<=millionth).*" data.txt);
echo "$fileContent" | grep -o -P "\w*";
exit' 2>/dev/null
