#!/bin/bash
name="14"
password="4wcYUJFw0k0XLShlDzztnTBHiqxU3b3e"
sshpass -p "$password" ssh -o StrictHostKeyChecking=no -p 2220 bandit"$name"@bandit.labs.overthewire.org '
response=$(echo "4wcYUJFw0k0XLShlDzztnTBHiqxU3b3e" | nc localhost 30000)
echo "$response" | grep -P "\w{32}"
exit' 2>/dev/null
